// Self-contained HTML report (inline CSS + a little vanilla JS, no deps).
// Centerpiece: an SVG "contract flow" — frontend resources on the left, backend
// resources on the right, links coloured green (matched) or red (drift).

const esc = (s) =>
  String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const seg = (p) => (String(p || '').split('/')[0] || '(root)');
const rel = (f) => String(f).replace(process.cwd() + '/', '');

// Compact "folder/file.ts:line" with the full path kept on hover.
const shortFile = (f) => {
  const p = String(f).split('/');
  return p.length > 2 ? p.slice(-2).join('/') : String(f);
};
const locCell = (file, line) =>
  `<td class="loc" title="${esc(rel(file))}${line ? ':' + line : ''}">${esc(shortFile(file))}${line ? ':' + line : ''}</td>`;

export function reportHtml(result, meta = {}) {
  const { matched = [], drift = [], unverifiable = [], dead = [], totals = {} } = result;
  const total = (totals.matched || 0) + (totals.drift || 0) + (totals.unverifiable || 0);
  const health = total ? Math.round((totals.matched / total) * 100) : 100;

  const flow = buildFlow(result);
  const svg = renderFlow(flow);

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>seam · contract report</title>
<style>${CSS}</style></head>
<body>
<header class="hero">
  <div class="hero-inner">
    <div class="brand"><span class="logo">⟡</span> seam<span class="sub">contract report</span></div>
    <div class="meta">
      <span>${esc(meta.clientAdapter || 'client')} <span class="arrow">↔</span> ${esc(meta.serverAdapter || 'server')}</span>
      ${meta.generatedAt ? `<span class="dim">${esc(meta.generatedAt)}</span>` : ''}
    </div>
  </div>
  <div class="ring" style="--p:${health}">
    <svg viewBox="0 0 120 120"><circle class="track" cx="60" cy="60" r="52"/><circle class="value ${health >= 90 ? 'ok' : health >= 70 ? 'warn' : 'bad'}" cx="60" cy="60" r="52"/></svg>
    <div class="ring-label"><strong>${health}%</strong><span>matched</span></div>
  </div>
</header>

<main>
  <section class="cards">
    ${card('matched', totals.matched || 0, 'ok', 'resolve to a real route')}
    ${card('drift', totals.drift || 0, 'bad', 'FE calls a missing route')}
    ${card('unverifiable', totals.unverifiable || 0, 'warn', 'url built at runtime')}
    ${card('unused routes', totals.dead || 0, 'mute', 'no FE call reaches them')}
  </section>

  <section class="panel">
    <h2>Contract flow</h2>
    <p class="hint">Frontend resources on the left, backend on the right. <span class="k ok">●</span> matched · <span class="k bad">●</span> drift · <span class="k mute">●</span> ∅ no backend route.${flow.truncated ? ` Showing the top ${flow.cap} resources per side; full detail in the tables below.` : ''}</p>
    <div class="flow">${svg}</div>
  </section>

  ${table('Drift', 'bad', drift, (d) => `
    <tr data-text="${esc(d.method + ' ' + d._np + ' ' + d.name)}">
      <td class="ep"><span class="verb ${d.method}">${esc(d.method)}</span><span class="path">/${esc(d._np)}</span>${d.name ? `<div class="sub">${esc(d.name)}</div>` : ''}</td>
      <td class="hintcell">${esc(d.hint || '')}</td>
      ${locCell(d.file, d.line)}
    </tr>`, 'These frontend calls do not match any backend route.')}

  ${table('Unverifiable', 'warn', unverifiable, (u) => `
    <tr data-text="${esc((u.name || '') + ' ' + rel(u.file))}">
      <td class="dim" colspan="2">${esc(u.name || '(dynamic)')}</td>
      <td colspan="2" class="hintcell">url built at runtime — not statically resolvable</td>
      ${locCell(u.file, u.line)}
    </tr>`, 'Calls whose URL is assembled at runtime. Reported, never guessed.')}

  ${table('Unused backend routes', 'mute', dead, (r) => `
    <tr data-text="${esc(r.method + ' ' + r._np)}">
      <td><span class="verb ${r.method}">${esc(r.method)}</span></td>
      <td class="path" colspan="3">/${esc(r._np)}</td>
      ${locCell(r.file, r.line)}
    </tr>`, 'Backend routes no resolvable frontend call reaches (may be webhooks, admin, or other clients).')}
</main>

<footer>Generated by <strong>seam</strong> · static FE↔BE contract checker</footer>
<script>${JS}</script>
</body></html>`;
}

function card(label, value, kind, sub) {
  return `<div class="cardx ${kind}"><div class="num">${value}</div><div class="lab">${esc(label)}</div><div class="csub">${esc(sub)}</div></div>`;
}

function table(title, kind, rows, rowFn, blurb) {
  if (!rows.length) return `<section class="panel"><h2>${esc(title)} <span class="count ok">0</span></h2><p class="hint">None. ✅</p></section>`;
  return `<section class="panel">
    <h2>${esc(title)} <span class="count ${kind}">${rows.length}</span></h2>
    <p class="hint">${esc(blurb)}</p>
    <input class="filter" placeholder="Filter ${rows.length} rows…" oninput="filterRows(this)">
    <table><tbody>${rows.map(rowFn).join('')}</tbody></table>
  </section>`;
}

// ---- flow data + svg -----------------------------------------------------

function buildFlow(result) {
  const cap = 12;
  const fe = new Map();
  const bump = (m, k, f) => { const v = m.get(k) || { matched: 0, drift: 0 }; v[f]++; m.set(k, v); };
  for (const e of result.matched) bump(fe, seg(e._np), 'matched');
  for (const e of result.drift) bump(fe, seg(e._np), 'drift');

  const beNames = new Set();
  for (const e of result.matched) beNames.add(seg(e._np));
  for (const r of result.dead) beNames.add(seg(r._np));

  const linkAgg = new Map();
  const addLink = (from, to, kind) => {
    const k = `${from}|${to}|${kind}`;
    linkAgg.set(k, (linkAgg.get(k) || 0) + 1);
  };
  for (const e of result.matched) addLink(seg(e._np), seg(e._np), 'matched');
  let usedMissing = false;
  for (const e of result.drift) {
    const s = seg(e._np);
    const to = beNames.has(s) ? s : '∅';
    if (to === '∅') usedMissing = true;
    addLink(s, to, 'drift');
  }

  // Rank + cap each side.
  const score = (v) => v.matched + v.drift * 2;
  const feNodes = [...fe.entries()].sort((a, b) => score(b[1]) - score(a[1]));
  const truncated = feNodes.length > cap || beNames.size > cap;
  const feTop = feNodes.slice(0, cap).map(([name]) => name);
  const feSet = new Set(feTop);

  const beAll = [...beNames].sort();
  const beTop = beAll.filter((n) => feSet.has(n)).concat(beAll.filter((n) => !feSet.has(n))).slice(0, cap);
  if (usedMissing) beTop.push('∅');
  const beSet = new Set(beTop);

  const links = [];
  for (const [k, count] of linkAgg) {
    const [from, to, kind] = k.split('|');
    if (feSet.has(from) && beSet.has(to)) links.push({ from, to, kind, count });
  }
  return { fe: feTop, be: beTop, links, feMeta: fe, cap, truncated };
}

function renderFlow({ fe, be, links, feMeta }) {
  if (!fe.length && !be.length) return '<p class="hint">No resolved endpoints to chart.</p>';
  const W = 920, rowH = 46, top = 16, nodeW = 230, nodeH = 32;
  const rows = Math.max(fe.length, be.length, 1);
  const H = top * 2 + rows * rowH;
  const leftX = 20, rightX = W - 20 - nodeW;
  const yOf = (i) => top + i * rowH + nodeH / 2;
  const fi = new Map(fe.map((n, i) => [n, i]));
  const bi = new Map(be.map((n, i) => [n, i]));

  const linkSvg = links
    .sort((a) => (a.kind === 'matched' ? -1 : 1))
    .map((l) => {
      const y1 = yOf(fi.get(l.from)), y2 = yOf(bi.get(l.to));
      const x1 = leftX + nodeW, x2 = rightX;
      const c = Math.round((x1 + x2) / 2);
      const w = Math.max(1.5, Math.min(8, l.count));
      const cls = l.to === '∅' ? 'missing' : l.kind;
      return `<path class="link ${cls}" d="M${x1},${y1} C${c},${y1} ${c},${y2} ${x2},${y2}" stroke-width="${w}" data-from="${esc(l.from)}"><title>${esc(l.from)} → ${esc(l.to)}: ${l.count} ${l.kind}</title></path>`;
    })
    .join('');

  const node = (name, x, i, side) => {
    const meta = feMeta.get(name);
    const bad = side === 'left' && meta && meta.drift > 0;
    const miss = name === '∅';
    const badge = meta ? `<tspan class="badge">${meta.matched + meta.drift}</tspan>` : '';
    return `<g class="node ${bad ? 'bad' : ''} ${miss ? 'missing' : ''}" data-res="${esc(name)}">
      <rect x="${x}" y="${top + i * rowH}" rx="8" width="${nodeW}" height="${nodeH}"/>
      <text x="${x + 14}" y="${top + i * rowH + 21}">${esc(miss ? '∅  no backend route' : '/' + name)} ${badge}</text>
    </g>`;
  };

  return `<svg viewBox="0 0 ${W} ${H}" class="flowsvg" role="img" aria-label="contract flow">
    <text class="col" x="${leftX + 6}" y="10">FRONTEND</text>
    <text class="col" x="${rightX + nodeW - 6}" y="10" text-anchor="end">BACKEND</text>
    ${linkSvg}
    ${fe.map((n, i) => node(n, leftX, i, 'left')).join('')}
    ${be.map((n, i) => node(n, rightX, i, 'right')).join('')}
  </svg>`;
}

const CSS = `
:root{--bg:#0b0f1a;--panel:#121829;--ink:#e7ecf5;--dim:#8b97b0;--line:#222c44;--ok:#22c55e;--bad:#f43f5e;--warn:#f59e0b;--mute:#64748b;--accent:#6366f1}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#0b0f1a,#0d1322);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
.hero{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:34px 40px;background:radial-gradient(1200px 200px at 10% -40%,rgba(99,102,241,.35),transparent),linear-gradient(90deg,#11162a,#0e1424);border-bottom:1px solid var(--line)}
.brand{font-size:30px;font-weight:800;letter-spacing:-.5px}.logo{color:var(--accent)}.sub{font-size:13px;color:var(--dim);font-weight:600;margin-left:10px;text-transform:uppercase;letter-spacing:2px}
.meta{margin-top:8px;color:var(--dim);font-size:14px;display:flex;gap:16px;flex-wrap:wrap}.arrow{color:var(--accent)}.dim{color:var(--dim)}
.ring{position:relative;width:120px;height:120px;flex:none}.ring svg{transform:rotate(-90deg)}
.ring circle{fill:none;stroke-width:12}.track{stroke:#1c2540}.value{stroke:var(--ok);stroke-linecap:round;stroke-dasharray:calc(var(--p)*3.267) 1000;transition:stroke-dasharray .6s}
.value.warn{stroke:var(--warn)}.value.bad{stroke:var(--bad)}
.ring-label{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}.ring-label strong{font-size:26px}.ring-label span{font-size:11px;color:var(--dim);text-transform:uppercase;letter-spacing:1px}
main{max-width:1000px;margin:0 auto;padding:28px 24px 60px}
.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:26px}
.cardx{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px 18px 16px;position:relative;overflow:hidden}
.cardx::before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px}
.cardx.ok::before{background:var(--ok)}.cardx.bad::before{background:var(--bad)}.cardx.warn::before{background:var(--warn)}.cardx.mute::before{background:var(--mute)}
.cardx .num{font-size:34px;font-weight:800;letter-spacing:-1px}.cardx.ok .num{color:var(--ok)}.cardx.bad .num{color:var(--bad)}.cardx.warn .num{color:var(--warn)}.cardx.mute .num{color:var(--mute)}
.cardx .lab{font-weight:700;text-transform:capitalize}.csub{color:var(--dim);font-size:12.5px;margin-top:2px}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px 22px;margin-bottom:22px}
.panel h2{margin:0 0 4px;font-size:18px;display:flex;align-items:center;gap:10px}
.count{font-size:13px;font-weight:700;padding:2px 10px;border-radius:999px}.count.bad{background:rgba(244,63,94,.15);color:var(--bad)}.count.warn{background:rgba(245,158,11,.15);color:var(--warn)}.count.mute{background:rgba(100,116,139,.18);color:#9aa7bd}.count.ok{background:rgba(34,197,94,.15);color:var(--ok)}
.hint{color:var(--dim);font-size:13px;margin:.2em 0 1em}.k{font-size:11px;vertical-align:middle}.k.ok{color:var(--ok)}.k.bad{color:var(--bad)}.k.mute{color:var(--mute)}
.flow{overflow-x:auto}.flowsvg{width:100%;height:auto;min-width:680px}
.col{fill:var(--dim);font-size:10px;font-weight:700;letter-spacing:2px}
.node rect{fill:#0e1730;stroke:var(--line)}.node text{fill:var(--ink);font-size:13px;font-weight:600}
.node .badge{fill:var(--dim);font-size:11px;font-weight:700}
.node.bad rect{stroke:var(--bad)}.node.missing rect{stroke:var(--mute);stroke-dasharray:4 3}.node.missing text{fill:var(--mute)}
.node:hover rect{filter:brightness(1.4)}
.link{fill:none;opacity:.55;transition:opacity .15s}.link.matched{stroke:var(--ok)}.link.drift{stroke:var(--bad);stroke-dasharray:6 4}.link.missing{stroke:var(--mute);stroke-dasharray:2 4}
.flowsvg:hover .link{opacity:.18}.flowsvg .link:hover{opacity:1}
.filter{width:100%;background:#0d1426;border:1px solid var(--line);border-radius:9px;color:var(--ink);padding:9px 12px;margin-bottom:12px;font:13px ui-monospace,monospace}
table{width:100%;border-collapse:collapse;font:12.5px ui-monospace,SFMono-Regular,Menlo,monospace}
tbody tr:hover{background:rgba(99,102,241,.07)}
td{padding:5px 10px;border-top:1px solid var(--line);vertical-align:top}
.verb{display:inline-block;min-width:50px;text-align:center;font-weight:700;font-size:10.5px;letter-spacing:.5px;padding:2px 6px;border-radius:6px;background:#18203a}
.verb.GET{color:#38bdf8}.verb.POST{color:#34d399}.verb.PUT,.verb.PATCH{color:#fbbf24}.verb.DELETE{color:#fb7185}.verb.ALL{color:#a78bfa}
.path{font-weight:600;overflow-wrap:anywhere}.hintcell{color:var(--warn)}
.ep .path{margin-left:8px}.sub{color:var(--dim);font-size:11px;margin-top:3px}
.loc{color:var(--dim);text-align:right;white-space:nowrap;cursor:default}.loc:hover{color:var(--ink)}
td.dim{color:var(--dim)}
footer{text-align:center;color:var(--dim);font-size:13px;padding:24px}
@media(max-width:680px){.cards{grid-template-columns:repeat(2,1fr)}.hero{flex-direction:column;align-items:flex-start}}
`;

const JS = `
function filterRows(input){var q=input.value.toLowerCase();var rows=input.parentNode.querySelectorAll('tbody tr');rows.forEach(function(r){r.style.display=(r.getAttribute('data-text')||'').toLowerCase().indexOf(q)>-1?'':'none'});}
document.querySelectorAll('.node').forEach(function(n){n.addEventListener('mouseenter',function(){var res=n.getAttribute('data-res');document.querySelectorAll('.link').forEach(function(l){l.style.opacity=l.getAttribute('data-from')===res?'1':'.12'})});n.addEventListener('mouseleave',function(){document.querySelectorAll('.link').forEach(function(l){l.style.opacity=''})});});
`;
